remote_theme : artemsheludko/flexible-jekyll

title: Hello, world! I'm SantJ
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "http://tmdwo5811.github.io" # the subpath of your site, e.g. /blog
url: "http://tmdwo5811.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: SANT_J  SeungJae Yoon # add your name
author-img: KakaoTalk_20200121_160404696.png # add your photo
about-author: 개인 설명 좌르르르륵  # add description
social-twitter: none # add your Twitter handle
social-facebook: seungjae.yoon.77 # add your Facebook handle
social-github: tmdwo5811 # add your Github handle
social-linkedin: none # add your Linkedin handle
social-email: tmdwo5811@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]